apiVersion: ops.kubedb.com/v1alpha1
kind: ElasticsearchOpsRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ops.kubedb.com/v1alpha1","kind":"ElasticsearchOpsRequest","metadata":{"annotations":{},"name":"myops-reconfigure-config","namespace":"demo"},"spec":{"configuration":{"configSecret":{"name":"es-custom-config"}},"databaseRef":{"name":"es-quickstart"},"type":"Reconfigure"}}
  creationTimestamp: "2023-08-07T08:22:13Z"
  generation: 1
  name: myops-reconfigure-config
  namespace: demo
  resourceVersion: "185703"
  uid: c0aeb572-23f4-4d72-a1f6-5d392317ab85
spec:
  apply: IfReady
  configuration:
    configSecret:
      name: es-custom-config
  databaseRef:
    name: es-quickstart
  type: Reconfigure
status:
  conditions:
  - lastTransitionTime: "2023-08-07T08:22:14Z"
    message: Elasticsearch ops request is reconfiguring the cluster
    observedGeneration: 1
    reason: Reconfigure
    status: "True"
    type: Reconfigure
  - lastTransitionTime: "2023-08-07T08:22:14Z"
    message: Successfully updated statefulsets
    observedGeneration: 1
    reason: UpdateStatefulSets
    status: "True"
    type: UpdateStatefulSets
  - lastTransitionTime: "2023-08-07T08:24:59Z"
    message: Successfully restarted all nodes
    observedGeneration: 1
    reason: RestartNodes
    status: "True"
    type: RestartNodes
  - lastTransitionTime: "2023-08-07T08:24:59Z"
    message: Successfully completed the modification process.
    observedGeneration: 1
    reason: Successful
    status: "True"
    type: Successful
  observedGeneration: 1
  phase: Successful
