apiVersion: kubedb.com/v1alpha2
kind: Elasticsearch
metadata:
  name: os-quickstart
  namespace: demo
spec:
  version: opensearch-2.8.0
  enableSSL: true
  replicas: 2
  monitor:
    agent: prometheus.io
    prometheus:
      exporter:
        port: 56790
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Delete
