apiVersion: ops.kubedb.com/v1alpha1
kind: ElasticsearchOpsRequest
metadata:
  name: hscale-topology-downscale
  namespace: demo
spec:
  type: HorizontalScaling
  databaseRef:
    name: es-quickstart
  horizontalScaling:
    topology:
      data: 1

