apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: es-dev-backup
  namespace: elastic
spec:
  target:
    apiGroup: kubedb.com
    kind: Elasticsearch
    namespace: elastic
    name: es-dev
  backends:
  - name: s3-backend
    storageRef:
      namespace: elastic
      name: s3-store
    retentionPolicy:
      name: es-dev-retention-policy
      namespace: elastic
  sessions:
  - name: es-dev-frequent-backup
    sessionHistoryLimit: 10
    scheduler:
      schedule: "*/1 * * * *"
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      jobTemplate:
        backoffLimit: 1
    repositories:
    - name: es-dev-s3-repo
      backend: s3-backend
      directory: /sample/kubestashs/es-dev
      encryptionSecret:
        name: encry-secret # some addon may not support encryption
        namespace: elastic
    addon:
      name: elasticsearch
      tasks:
      - name: backup-es
      jobTemplate:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
