apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: db-backup
  namespace: dm
spec:
  target:
    apiGroup: kubedb.com
    kind: Elasticsearch
    namespace: dm
    name: es-quickstart
  backends:
  - name: s3-backend
    storageRef:
      namespace: dm
      name: s3-store
    retentionPolicy:
      name: rp
      namespace: dm
  sessions:
  - name: frequent-backup
    sessionHistoryLimit: 10
    scheduler:
      schedule: "*/1 * * * *"
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      jobTemplate:
        backoffLimit: 1
    repositories:
    - name: s3-repo-els
      backend: s3-backend
      directory: /sample/kubestashs/els
      encryptionSecret:
        name: encry-secret # some addon may not support encryption
        namespace: dm
    addon:
      name: elasticsearch
      tasks:
      - name: backup-es
      jobTemplate:
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
    #     targetVolumes:
    #       volumeMounts:
    #       - name: source-data
    #         mountPath: /source/data
    #     params:
    #       paths: /source/data
    # retryConfig:
    #   maxRetry: 2
    #   delay: 1m
