apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: s3-store
  namespace: elastic
spec:
  storage:
    provider: s3
    s3:                                                              # eg. s3, gcs, azure, swift, b2 
      endpoint: ap-south-1.linodeobjects.com
      bucket: pds
      region: ap-south-1
      prefix: elastic
      secret: s3-secret
  usagePolicy:
    allowedNamespaces:
      from: All
  default: true 
  deletionPolicy: WipeOut                                           # eg Delete, Wipeout
