apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: es-dev-restore
  namespace: elastic
spec:
  target:
    name: es-dev
    namespace: elastic
    apiGroup: kubedb.com
    kind: Elasticsearch
  dataSource:
    snapshot: es-dev-s3-repo-es-dev-backup-es-dev-frequent-backup-1700544300
    repository: es-dev-s3-repo
    encryptionSecret:
      name: encry-secret 
      namespace: elastic
  addon:
    name: elasticsearch
    tasks:
    - name: restore-es
    jobTemplate:
      spec:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
