apiVersion: ops.kubedb.com/v1alpha1
kind: ElasticsearchOpsRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ops.kubedb.com/v1alpha1","kind":"ElasticsearchOpsRequest","metadata":{"annotations":{},"name":"volume-expansion-topology","namespace":"demo"},"spec":{"databaseRef":{"name":"es-quickstart"},"type":"VolumeExpansion","volumeExpansion":{"topology":{"data":"4Gi"}}}}
  creationTimestamp: "2023-08-07T11:42:30Z"
  generation: 1
  name: volume-expansion-topology
  namespace: demo
  resourceVersion: "9176"
  uid: 029a2ec8-8a16-495b-b2a4-0e7e82f2300f
spec:
  apply: IfReady
  databaseRef:
    name: es-quickstart
  type: VolumeExpansion
  volumeExpansion:
    mode: Online
    topology:
      data: 4Gi
status:
  conditions:
  - lastTransitionTime: "2023-08-07T11:42:30Z"
    message: Elasticsearch ops request is expanding volume of the Elasticsearch nodes.
    observedGeneration: 1
    reason: VolumeExpansion
    status: "True"
    type: VolumeExpansion
  - lastTransitionTime: "2023-08-07T11:42:45Z"
    message: successfully deleted the statefulSets with orphan propagation policy
    observedGeneration: 1
    reason: OrphanStatefulSetPods
    status: "True"
    type: OrphanStatefulSetPods
  - lastTransitionTime: "2023-08-07T11:43:20Z"
    message: successfully updated data node PVC sizes
    observedGeneration: 1
    reason: VolumeExpansionDataNode
    status: "True"
    type: VolumeExpansionDataNode
  - lastTransitionTime: "2023-08-07T11:43:25Z"
    message: successfully reconciled the Elasticsearch resources
    observedGeneration: 1
    reason: UpdateStatefulSets
    status: "True"
    type: UpdateStatefulSets
  - lastTransitionTime: "2023-08-07T11:43:31Z"
    message: StatefulSet is recreated
    observedGeneration: 1
    reason: ReadyStatefulSets
    status: "True"
    type: ReadyStatefulSets
  - lastTransitionTime: "2023-08-07T11:43:37Z"
    message: successfully updated Elasticsearch CR
    observedGeneration: 1
    reason: UpdateDatabase
    status: "True"
    type: UpdateDatabase
  - lastTransitionTime: "2023-08-07T11:43:38Z"
    message: Successfully completed the modification process.
    observedGeneration: 1
    reason: Successful
    status: "True"
    type: Successful
  observedGeneration: 1
  phase: Successful
