apiVersion: ops.kubedb.com/v1alpha1
kind: ElasticsearchOpsRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ops.kubedb.com/v1alpha1","kind":"ElasticsearchOpsRequest","metadata":{"annotations":{},"name":"vscale-topology","namespace":"demo"},"spec":{"databaseRef":{"name":"es-quickstart"},"type":"VerticalScaling","verticalScaling":{"topology":{"master":{"limits":{"cpu":"800m","memory":"1.5Gi"},"requests":{"cpu":"800m","memory":"1.5Gi"}}}}}}
  creationTimestamp: "2023-08-07T04:26:37Z"
  generation: 1
  name: vscale-topology
  namespace: demo
  resourceVersion: "158489"
  uid: 94be3410-0447-4e0b-9994-d17590ffd864
spec:
  apply: IfReady
  databaseRef:
    name: es-quickstart
  type: VerticalScaling
  verticalScaling:
    topology:
      master:
        limits:
          cpu: 800m
          memory: 1.5Gi
        requests:
          cpu: 800m
          memory: 1.5Gi
status:
  conditions:
  - lastTransitionTime: "2023-08-07T04:26:37Z"
    message: Elasticsearch ops request is vertically scaling the nodes
    observedGeneration: 1
    reason: VerticalScale
    status: "True"
    type: VerticalScale
  - lastTransitionTime: "2023-08-07T04:26:42Z"
    message: successfully reconciled the Elasticsearch resources
    observedGeneration: 1
    reason: UpdateStatefulSets
    status: "True"
    type: UpdateStatefulSets
  - lastTransitionTime: "2023-08-07T04:27:32Z"
    message: Successfully restarted all nodes
    observedGeneration: 1
    reason: RestartNodes
    status: "True"
    type: RestartNodes
  - lastTransitionTime: "2023-08-07T04:27:37Z"
    message: successfully updated Elasticsearch CR
    observedGeneration: 1
    reason: UpdateDatabase
    status: "True"
    type: UpdateDatabase
  - lastTransitionTime: "2023-08-07T04:27:37Z"
    message: Successfully completed the modification process.
    observedGeneration: 1
    reason: Successful
    status: "True"
    type: Successful
  observedGeneration: 1
  phase: Successful

