apiVersion: ops.kubedb.com/v1alpha1
kind: ElasticsearchOpsRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ops.kubedb.com/v1alpha1","kind":"ElasticsearchOpsRequest","metadata":{"annotations":{},"name":"rotate-tls","namespace":"demo"},"spec":{"databaseRef":{"name":"es-quickstart"},"tls":{"rotateCertificates":true},"type":"ReconfigureTLS"}}
  creationTimestamp: "2023-08-07T08:13:22Z"
  generation: 1
  name: rotate-tls
  namespace: demo
  resourceVersion: "184185"
  uid: f6852742-0d59-440d-a120-f52035bf2ac1
spec:
  apply: IfReady
  databaseRef:
    name: es-quickstart
  tls:
    rotateCertificates: true
  type: ReconfigureTLS
status:
  conditions:
  - lastTransitionTime: "2023-08-07T08:13:22Z"
    message: Elasticsearch ops request is reconfiguring TLS
    observedGeneration: 1
    reason: ReconfigureTLS
    status: "True"
    type: ReconfigureTLS
  - lastTransitionTime: "2023-08-07T08:13:22Z"
    message: successfully add issuing condition to all the certificates
    observedGeneration: 1
    reason: IssueCertificatesSucceeded
    status: "True"
    type: IssueCertificatesSucceeded
  - lastTransitionTime: "2023-08-07T08:13:27Z"
    message: Successfully synced all certificates
    observedGeneration: 1
    reason: CertificateSynced
    status: "True"
    type: CertificateSynced
  - lastTransitionTime: "2023-08-07T08:15:53Z"
    message: Successfully restarted all the nodes
    observedGeneration: 1
    reason: RestartNodes
    status: "True"
    type: RestartNodes
  - lastTransitionTime: "2023-08-07T08:15:53Z"
    message: Successfully reconfigured TLS
    observedGeneration: 1
    reason: Successful
    status: "True"
    type: Successful
  observedGeneration: 1
  phase: Successful
